MYWIFI_SSID = "WIFI_SSID"
MYWIFI_PASSWORD = "WIFI_PASSWORD"
JEEDOM_IP = "192.168.0.0"
JEEDOM_MQTT_USER = "user_mqtt"
JEEDOM_MQTT_PASSWORD = "password_mqtt"
JEEDOM_OBJECT_NAME_MQTT = "RGB_Matrix_LED_1"